### PR TITLE
Wideband Rev2 board and other fixes

### PR DESCRIPTION
**Pull request by dron0gus**

### CODE REVIEW

**Comment by rusefillc** [comment]
@dron0gus plz fetch your master

image

and rebase this PR on your master I think it would make cherry picking and merging simpler, as is board commits in this PR are in conflict with master if I see things right

**Comment by rusefillc** [comment]
@dron0gus case in point https://github.com/mck1117/wideband/pull/62

**Comment by dron0gus** [comment]
> @dron0gus plz fetch your master
> 
> image
> 
> and rebase this PR on your master I think it would make cherry picking and merging simpler, as is board commits in this PR are in conflict with master if I see things right

This master is away from @mck1117 master...

**Comment by dron0gus** [comment]
rebased, forse-pushed, now I want to merge it with master.

**Comment by mck1117** [comment]
please pr in to mck1117/wideband instead, why do we pr here?

**Comment by dron0gus** [comment]
Sorry, this is abandoned PR.

**Pull request closed without merging**
